### ISSUE TITLE
Styling Meeting Minutes with External CSS

### ISSUE THREAD

**Issue by dwk002** [dwk002/fa21-cse110-lab3#2]
**Issue Name:** Styling with CSS 
**Issue Description:** Modify Meeting Minutes with CSS
**Tasks:**
### General CSS Topics
- [ ] **Comment**
- [ ] **Color**
  - [ ] rgb(r, g, b)
  - [ ] #FFFFFF   
  - [ ] hsl(h, s, l) 
  - [ ] Color name (i.e ‘orange’)
- [ ] **Unit**
  - [ ] 3 unique relative units
  - [ ] 3 unique absolute units
- [ ] **Box Model**
  - [ ] border-style
  - [ ] border-color
  - [ ] border-width
  - [ ] border-radius
- [ ] **Text** 
  - [ ]  color
  - [ ] text-decoration
  - [ ] text-align
- [ ] **Display**
  - [ ] none or block, 
  - [ ] inline-block or inline
- [ ] **Sizing**
  - [ ] height
  - [ ] width
  - [ ] max-width
  - [ ] min-width    
- [ ] **Position**
  - [ ] position (property)
    - [ ] static or relative, 
    - [ ] fixed, absolute, or sticky
- [ ] **Pseudo Class**   
  - [ ] :hover
  - [ ] :active
- [ ] **Layouts**
  - [ ] _Flexbox_
    - [ ] apply ```flex``` to ```display``` property
    - [ ] Must have more than two children within the element that is using flexbox. Must use minimum three of the flexbox related attributes
  - [ ] _Grid_
    - [ ] apply ```grid``` to ```display``` property
    - [ ] Must have more than two children within the element that is using the grid. Must use a minimum of three of the grid related attributes
- [ ] **Responsiveness**
  - [ ] At least one query based on the screen width (Media Query)

### CSS Selector
- [ ] Class Selector (.class)
- [ ] ID Selector (#id)
- [ ] Universal Selector (*)
- [ ] Element Selector (element) 
- [ ] Attribute Selector (e.g. [attribute=foo])     
- [ ] Pseudo-class Selector (e.g. p:hover)
- [ ] Selector List (element, element)                   
- [ ] Combinators (you must use one of each)  
  - [ ] Descendant Combinator (element element)
  - [ ] Child Combinator (element > element)
  - [ ] General sibling combinator (element ~ element)
  - [ ] Adjacent sibling combinator (element + element)
  - [ ] Combining Two Selectors (element.class)
