### ISSUE TITLE
Styling Meeting Minutes with External CSS

### ISSUE THREAD

**Issue by dwk002** [dwk002/fa21-cse110-lab3#7]
**Issue Name:** Styling with CSS 
**Issue Description:** Modify Meeting Minutes with CSS
**Tasks:**
### General CSS Topics
- [x] **Comment**
- [x] **Color**
  - [x] rgb(r, g, b)
  - [x] #FFFFFF   
  - [x] hsl(h, s, l) 
  - [x] Color name (i.e ‘orange’)
- [x] Font 
- [x] **Unit**
  - [x] 3 unique relative units
  - [x] 3 unique absolute units
- [x] **Box Model**
  - [x] Both Long & Short
  - [x] Margin
  - [x] Margin Auto
  - [x] Padding
  - [x] border-style
  - [x] border-color
  - [x] border-width
  - [x] border-radius
- [x] **Text** 
  - [x]  color
  - [x] text-decoration
  - [x] text-align
- [x] **Display**
  - [x] none or block, 
  - [x] inline-block or inline
- [x] **Sizing**
  - [x] height
  - [x] width
  - [x] max-width
  - [x] min-width    
- [x] **Position**
  - [x] position (property)
    - [x] static or relative, 
    - [x] fixed, absolute, or sticky
- [x] **Pseudo Class**   
  - [x] :hover
  - [x] :active
- [x] **Layouts**
  - [x] _Flexbox_
    - [x] apply ```flex``` to ```display``` property
    - [x] Must have more than two children within the element that is using flexbox. Must use minimum three of the flexbox related attributes
  - [x] _Grid_
    - [x] apply ```grid``` to ```display``` property
    - [x] Must have more than two children within the element that is using the grid. Must use a minimum of three of the grid related attributes
- [x] **Responsiveness**
  - [x] At least one query based on the screen width (Media Query)

### CSS Selector
- [x] Class Selector (.class)
- [x] ID Selector (#id)
- [x] Universal Selector (*)
- [x] Element Selector (element) 
- [x] Attribute Selector (e.g. [attribute=foo])     
- [x] Pseudo-class Selector (e.g. p:hover)
- [x] Selector List (element, element)                   
- [x] Combinators (you must use one of each)  
  - [x] Descendant Combinator (element element)
  - [x] Child Combinator (element > element)
  - [x] General sibling combinator (element ~ element)
  - [x] Adjacent sibling combinator (element + element)
  - [x] Combining Two Selectors (element.class)

**Comment by dwk002** [comment]
Complete
